/**
 * Conversation History Domain Logic
 *
 * Pure functions for managing conversation history posts
 */

import { getZodiacDisplay } from '~/domain/zodiac';

// Maximum characters per history post (留 200 字符緩衝)
export const MAX_HISTORY_POST_CHARS = 3800;

/**
 * Format a message entry for history post
 */
export function formatMessageEntry(
  time: Date,
  direction: 'sent' | 'received',
  content: string,
  i18n?: any
): string {
  const timeStr = formatTime(time);
  const directionLabel =
    direction === 'sent'
      ? i18n?.t('conversationHistory.you') || '你'
      : i18n?.t('conversationHistory.other') || '對方';
  return `[${timeStr}] ${directionLabel}：${content}`;
}

/**
 * Format time as HH:MM
 */
function formatTime(date: Date): string {
  const hours = String(date.getHours()).padStart(2, '0');
  const minutes = String(date.getMinutes()).padStart(2, '0');
  return `${hours}:${minutes}`;
}

/**
 * Format date as YYYY-MM-DD HH:MM
 */
function formatDateTime(date: Date): string {
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, '0');
  const day = String(date.getDate()).padStart(2, '0');
  const hours = String(date.getHours()).padStart(2, '0');
  const minutes = String(date.getMinutes()).padStart(2, '0');
  return `${year}-${month}-${day} ${hours}:${minutes}`;
}

/**
 * Build history post content
 */
export function buildHistoryPostContent(
  identifier: string,
  postNumber: number,
  messages: string[],
  totalMessages: number,
  partnerInfo?: {
    maskedNickname: string;
    mbti: string;
    bloodType: string;
    zodiac: string;
    matchScore?: number;
  },
  isVip?: boolean,
  i18n?: any
): string {
  if (i18n) {
    let content = i18n.t('conversationHistory.title', { identifier, postNumber }) + '\n\n';

    // Add partner info at the top if provided
    if (partnerInfo) {
      // Build MBTI string: Code (Title)
      let mbtiDisplay = partnerInfo.mbti;
      const mbtiCode = partnerInfo.mbti; // Assuming partnerInfo.mbti contains the code (e.g., ESTJ)
      // Check if it's a valid code (basic check, or just try lookup)
      // Note: partnerInfo.mbti might already be localized "Not Set" if generated by handler without i18n context?
      // But typically it should be the code.
      // Let's try to lookup title.
      const mbtiTitle = i18n.t(`mbti.titles.${mbtiCode}`, { defaultValue: '' });
      if (mbtiTitle && mbtiTitle !== `mbti.titles.${mbtiCode}`) {
         mbtiDisplay = `${mbtiCode} (${mbtiTitle})`;
      }

      content += i18n.t('conversationHistory.partnerInfo') + '\n';
      content +=
        i18n.t('conversationHistory.nickname', { nickname: partnerInfo.maskedNickname }) + '\n';
      content += i18n.t('conversationHistory.mbti', { mbti: mbtiDisplay }) + '\n';
      content +=
        i18n.t('conversationHistory.bloodType', { bloodType: partnerInfo.bloodType }) + '\n';
      content += i18n.t('conversationHistory.zodiac', { zodiac: getZodiacDisplay(partnerInfo.zodiac, i18n) }) + '\n';
      if (partnerInfo.matchScore) {
        content +=
          i18n.t('conversationHistory.matchScore', { score: Math.round(partnerInfo.matchScore) }) +
          '\n';
      }
      content += '\n';
    }

    content += '━━━━━━━━━━━━━━━━\n\n';
    content += messages.join('\n') + '\n\n';
    content += '━━━━━━━━━━━━━━━━\n\n';
    content += i18n.t('conversationHistory.historyNote') + '\n';
    content += i18n.t('conversationHistory.totalMessages', { count: totalMessages }) + '\n';
    content +=
      i18n.t('conversationHistory.lastUpdated', { time: formatDateTime(new Date()) }) + '\n\n';
    content += i18n.t('conversationHistory.replyHint') + '\n';

    // Add VIP upgrade hint for free users
    if (isVip === false) {
      content += '\n' + i18n.t('conversationHistory.vipUnlockAvatar') + '\n';
      content += i18n.t('conversationHistory.vipLearnMore');
    }

    return content;
  }

  // Fallback to default Chinese (Deprecated/Legacy support)
  const fallbackTitle = `💬 與 #${identifier} 的對話記錄（第 ${postNumber} 頁）\n\n`;
  const fallbackPartnerInfo = partnerInfo
    ? `👤 對方資料：\n` +
      `📝 暱稱：${partnerInfo.maskedNickname}\n` +
      `🧠 MBTI：${partnerInfo.mbti}\n` +
      `🩸 血型：${partnerInfo.bloodType}\n` +
      `⭐ 星座：${partnerInfo.zodiac}\n` +
      (partnerInfo.matchScore ? `💫 配對度：${Math.round(partnerInfo.matchScore)}分\n` : '') +
      `\n`
    : '';
  const fallbackSeparator = `━━━━━━━━━━━━━━━━\n\n`;
  const fallbackHistoryNote = `💡 這是對話的歷史記錄\n`;
  const fallbackTotalMessages = `📊 總訊息數：${totalMessages} 則\n`;
  const fallbackLastUpdated = `📅 最後更新：${formatDateTime(new Date())}\n\n`;
  const fallbackReplyHint = `💬 直接按 /reply 回覆訊息聊天\n`;
  const fallbackVipUnlock =
    isVip === false ? `\n🔒 升級 VIP 解鎖對方清晰頭像\n💎 使用 /vip 了解更多` : '';

  return (
    fallbackTitle +
    fallbackPartnerInfo +
    fallbackSeparator +
    messages.join('\n') +
    '\n\n' +
    fallbackSeparator +
    fallbackHistoryNote +
    fallbackTotalMessages +
    fallbackLastUpdated +
    fallbackReplyHint +
    fallbackVipUnlock
  );
}

/**
 * Build new message post content
 */
export function buildNewMessagePostContent(
  identifier: string,
  messageContent: string,
  messageTime: Date,
  _conversationId: number,
  partnerInfo?: {
    maskedNickname: string;
    mbti: string;
    bloodType: string;
    zodiac: string;
    matchScore?: number;
  },
  i18n?: any,
  originalContent?: string
): string {
  if (i18n) {
    // Header: 📩 來自 {Nickname} 的新訊息：
    let content = i18n.t('conversationHistory.newMessageFrom', { 
      nickname: partnerInfo?.maskedNickname || identifier 
    }) + '\n\n';

    // Top Info: MBTI, Zodiac
    if (partnerInfo) {
      // Build MBTI string: Code (Title)
      let mbtiDisplay = partnerInfo.mbti;
      const mbtiCode = partnerInfo.mbti;
      // Try to lookup title
      const mbtiTitle = i18n.t(`mbti.titles.${mbtiCode}`, { defaultValue: '' });
      if (mbtiTitle && mbtiTitle !== `mbti.titles.${mbtiCode}`) {
         mbtiDisplay = `${mbtiCode} (${mbtiTitle})`;
      }

      content += i18n.t('conversationHistory.mbti', { mbti: mbtiDisplay }) + '\n';
      content += i18n.t('conversationHistory.zodiac', { zodiac: getZodiacDisplay(partnerInfo.zodiac, i18n) }) + '\n\n';
    }

    content += '━━━━━━━━━━━━━━━━\n';

    // Content Area: Original + Translated
    if (originalContent && originalContent !== messageContent) {
      content += `${i18n.t('conversationHistory.originalContent')}\n${originalContent}\n\n`;
      content += `${i18n.t('conversationHistory.translatedContent')}\n${messageContent}\n`;
    } else {
      content += `${messageContent}\n`;
    }
    
    content += '━━━━━━━━━━━━━━━━\n\n';

    // Footer / Hints (Buttons handled by service)
    return content;
  }

  // Fallback to default Chinese (Legacy)
  const nickname = partnerInfo?.maskedNickname || `#${identifier}`;
  const header = `📩 來自 ${nickname} 的新訊息：\n\n`;
  
  let info = '';
  if (partnerInfo) {
    info += `🧠 MBTI：${partnerInfo.mbti}\n`;
    info += `⭐ 星座：${partnerInfo.zodiac}\n\n`;
  }

  let body = '━━━━━━━━━━━━━━━━\n';
  if (originalContent && originalContent !== messageContent) {
    body += `[原文]\n${originalContent}\n\n`;
    body += `[翻譯]\n${messageContent}\n`;
  } else {
    body += `${messageContent}\n`;
  }
  body += '━━━━━━━━━━━━━━━━\n\n';

  return header + info + body;
}

/**
 * Check if adding a new message would exceed the character limit
 */
export function wouldExceedLimit(currentContent: string, newMessage: string): boolean {
  const newLength = currentContent.length + newMessage.length + 1; // +1 for newline
  return newLength > MAX_HISTORY_POST_CHARS;
}

/**
 * Extract messages array from history post content
 */
export function extractMessages(content: string): string[] {
  const lines = content.split('\n');
  const messages: string[] = [];
  let inMessageSection = false;

  for (const line of lines) {
    if (line.includes('━━━━━━━━━━━━━━━━')) {
      if (!inMessageSection) {
        inMessageSection = true;
        continue;
      } else {
        break;
      }
    }

    if (inMessageSection && line.trim()) {
      messages.push(line);
    }
  }

  return messages;
}
