/**
 * Legal Documents Content
 * 
 * This file contains the HTML content of legal documents.
 * Auto-generated from public/*.html files.
 * 
 * DO NOT EDIT THIS FILE MANUALLY!
 * Run: node scripts/generate-legal-docs.js
 */

export const LEGAL_DOCUMENTS = {
  privacy: `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>XunNi Privacy Policy</title>
    <style>
        /* CSS reset and styles */
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; background: #f9f9f9; padding: 40px 20px; }
        .container { max-width: 900px; margin: 0 auto; background: white; padding: 60px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); }
        h1 { color: #1a1a1a; font-size: 32px; margin-bottom: 10px; border-bottom: 2px solid #eee; padding-bottom: 20px; }
        .version { color: #666; font-size: 14px; margin-bottom: 40px; font-style: italic; }
        h2 { color: #2c3e50; font-size: 24px; margin-top: 40px; margin-bottom: 20px; font-weight: 700; }
        h3 { color: #34495e; font-size: 18px; margin-top: 25px; margin-bottom: 15px; font-weight: 600; }
        p { margin-bottom: 15px; text-align: justify; }
        ul { margin-left: 20px; margin-bottom: 20px; }
        li { margin-bottom: 8px; }
        .notice-box { padding: 20px; border-radius: 6px; margin: 30px 0; border-left: 4px solid; }
        .info { background-color: #f0f7ff; border-color: #3498db; color: #2980b9; }
        .success { background-color: #f6ffed; border-color: #52c41a; color: #389e0d; }
        .warning { background-color: #fff3f3; border-color: #e74c3c; color: #c0392b; }
        .section-break { border-top: 1px solid #eee; margin: 40px 0; }
        a { color: #3498db; text-decoration: none; }
        a:hover { text-decoration: underline; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Privacy Policy</h1>
        <p class="version">Effective Date: January 18, 2025 | Version 2.1</p>

        <div class="notice-box info">
            <strong>PRIVACY COMMITMENT</strong><br>
            XunNi ("we", "us", or "Service") respects your privacy. This policy outlines how we handle your data in compliance with international standards (including GDPR principles where applicable). <strong>This English version shall prevail over any translations.</strong>
        </div>

        <h2>1. Information We Collect</h2>
        <h3>1.1 Information You Provide</h3>
        <ul>
            <li><strong>Registration Data:</strong> Telegram User ID, Username, Display Name.</li>
            <li><strong>Profile Data:</strong> Nickname, Gender, Date of Birth, Time of Birth, Place of Birth.</li>
            <li><strong>Psychometric Data:</strong> MBTI test results, self-reported interests.</li>
        </ul>
        <p><em>Note on Birth Data: We collect precise birth time and location solely for the purpose of generating astrological charts. This is a core functionality of the Service.</em></p>

        <h3>1.2 Automatically Collected Information</h3>
        <ul>
            <li><strong>Usage Data:</strong> Interaction logs (bottles thrown/caught), feature usage statistics.</li>
            <li><strong>Technical Data:</strong> Device settings, language preference (via Telegram API).</li>
        </ul>

        <h2>2. Legal Basis & Purpose of Processing</h2>
        <p>We process your data based on the following legal grounds:</p>
        <ul>
            <li><strong>Performance of Contract:</strong> To provide the fortune-telling, matching, and anonymous chat services you requested.</li>
            <li><strong>Legitimate Interest:</strong> To maintain platform security, prevent fraud, and enforce our Terms of Service (e.g., age verification, anti-spam).</li>
            <li><strong>Consent:</strong> For optional features where you explicitly provide data (e.g., survey responses).</li>
        </ul>

        <h2>3. Data Usage & Matching Privacy</h2>
        <h3>3.1 Social Matching</h3>
        <p>The Service allows users to generate compatibility reports. In this process:</p>
        <div class="notice-box success">
            <strong>PRIVACY BY DESIGN: Data Blindness</strong><br>
            Your raw personal data (Birth Date/Time/Location) is processed server-side only. We <strong>NEVER</strong> disclose this raw data to other users during the matching process. Other users only receive the <em>derived</em> compatibility insights (e.g., "High Compatibility").
        </div>

        <h2>4. Data Sharing & International Transfers</h2>
        <p>We do not sell your personal data. We share data only with:</p>
        <ul>
            <li><strong>Service Providers:</strong> Cloudflare (Infrastructure/DB), OpenAI/Google (Translation/AI Processing - Anonymized where possible).</li>
            <li><strong>Legal Authorities:</strong> If required by law or to protect rights and safety.</li>
        </ul>
        <p><strong>International Transfer:</strong> Your data is stored in Cloudflare's distributed database (D1), which may replicate data across multiple jurisdictions to ensure low latency and high availability.</p>

        <h2>5. Data Retention & Deletion</h2>
        <h3>5.1 Retention Period</h3>
        <p>We retain personal data as long as your account is active. Chat logs and temporary data may be auto-deleted after a set period (e.g., 90 days).</p>

        <h3>5.2 Account Deletion ("Right to be Forgotten")</h3>
        <p>You may request deletion via <code>/delete_me</code>. Upon confirmation:</p>
        <ul>
            <li><strong>Deleted:</strong> All personal profile data, chat history, and social graph data.</li>
            <li><strong>Retained (Legitimate Interest):</strong>
                <ul>
                    <li><strong>Financial Records:</strong> Transaction history (retained for tax/audit purposes).</li>
                    <li><strong>Security Blocklist:</strong> Your Telegram ID hash (retained permanently to enforce the ban on re-registration and prevent ban evasion).</li>
                </ul>
            </li>
        </ul>

        <h2>6. Security Measures</h2>
        <p>We employ industry-standard security measures including HTTPS/TLS encryption for data in transit and strict access controls for our databases. However, no internet transmission is 100% secure.</p>

        <h2>7. Children's Privacy</h2>
        <p>The Service is strictly for users aged 18 and over. We do not knowingly collect data from minors. If we discover such data, we will delete it immediately.</p>

        <h2>8. Contact Us</h2>
        <p>For any privacy-related inquiries or to exercise your data rights, please contact:</p>
        <div class="notice-box info">
            <strong>Email:</strong> privacy@xunni.app<br>
            <strong>Telegram Support:</strong> @xunni_support
        </div>

        <div class="section-break"></div>
        <p style="text-align: center; color: #999; font-size: 12px;">© 2025 XunNi. All Rights Reserved.</p>
    </div>
</body>
</html>`,
  
  terms: `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>XunNi Terms of Service</title>
    <style>
        /* CSS reset and styles */
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; line-height: 1.6; color: #333; background: #f9f9f9; padding: 40px 20px; }
        .container { max-width: 900px; margin: 0 auto; background: white; padding: 60px; border-radius: 8px; box-shadow: 0 4px 6px rgba(0,0,0,0.05); }
        h1 { color: #1a1a1a; font-size: 32px; margin-bottom: 10px; border-bottom: 2px solid #eee; padding-bottom: 20px; }
        .version { color: #666; font-size: 14px; margin-bottom: 40px; font-style: italic; }
        h2 { color: #2c3e50; font-size: 24px; margin-top: 40px; margin-bottom: 20px; font-weight: 700; }
        h3 { color: #34495e; font-size: 18px; margin-top: 25px; margin-bottom: 15px; font-weight: 600; }
        p { margin-bottom: 15px; text-align: justify; }
        ul { margin-left: 20px; margin-bottom: 20px; }
        li { margin-bottom: 8px; }
        .notice-box { padding: 20px; border-radius: 6px; margin: 30px 0; border-left: 4px solid; }
        .warning { background-color: #fff3f3; border-color: #e74c3c; color: #c0392b; }
        .info { background-color: #f0f7ff; border-color: #3498db; color: #2980b9; }
        .success { background-color: #f6ffed; border-color: #52c41a; color: #389e0d; }
        .section-break { border-top: 1px solid #eee; margin: 40px 0; }
        a { color: #3498db; text-decoration: none; }
        a:hover { text-decoration: underline; }
    </style>
</head>
<body>
    <div class="container">
        <h1>Terms of Service</h1>
        <p class="version">Effective Date: January 18, 2025 | Version 2.1</p>

        <div class="notice-box warning">
            <strong>⚠️ LEGAL DISCLAIMER & BINDING AGREEMENT</strong><br>
            Please read these Terms of Service ("Terms") carefully. By accessing or using XunNi ("Service"), you agree to be bound by these Terms. <strong>This English version shall prevail over any translations.</strong>
        </div>

        <h2>1. Nature of Service: Entertainment Only</h2>
        <p>The Service provides automated fortune-telling, personality analysis, and social matching features based on Artificial Intelligence (AI) and traditional astrological algorithms.</p>
        
        <div class="notice-box info">
            <strong>FOR ENTERTAINMENT PURPOSES ONLY</strong><br>
            All content, reports, predictions, and advice generated by the Service are for <strong>novelty and entertainment purposes only</strong>.
            <ul>
                <li><strong>No Professional Advice:</strong> The Service does not provide medical, legal, financial, or psychological advice.</li>
                <li><strong>No Reliance:</strong> You should not rely on the Service for any major life decisions (e.g., marriage, investment, health).</li>
                <li><strong>AI Limitations:</strong> AI-generated content may contain inaccuracies, errors, or "hallucinations". The Operator assumes no liability for the accuracy or reliability of such content.</li>
            </ul>
        </div>

        <h2>2. Social & Matching Authorization (Implied Consent)</h2>
        <p>XunNi is a social discovery platform. By registering an account, you explicitly acknowledge and grant the following authorizations as a condition of service:</p>
        
        <h3>2.1 Unilateral Matching Consent</h3>
        <p>You authorize other users to initiate "Compatibility Analysis" or "Fortune Matching" using your public profile (Nickname/ID) and derived astrological data. This process may occur unilaterally without specific notification to you for each instance.</p>

        <h3>2.2 Data Privacy in Matching</h3>
        <p>While you consent to the matching process, we guarantee strict data privacy:</p>
        <ul>
            <li><strong>Data Blindness:</strong> Your raw personal data (Birth Date, Time, Exact Location) is <strong>never</strong> disclosed to the matching party.</li>
            <li><strong>Result Only:</strong> The matching party receives only the derived analysis result (e.g., "85% Compatible", "Karmic Link").</li>
        </ul>

        <h2>3. User Conduct & Eligibility</h2>
        <h3>3.1 Eligibility</h3>
        <p>You must be at least 18 years of age to use the Service. Use by minors is strictly prohibited.</p>

        <h3>3.2 Prohibited Activities</h3>
        <p>You agree not to use the Service for:</p>
        <ul>
            <li>Fraud, scams, or financial solicitation.</li>
            <li>Harassment, hate speech, or explicit content distribution.</li>
            <li>Automated data scraping or botting.</li>
        </ul>

        <h2>4. Payment & Virtual Goods</h2>
        <h3>4.1 Pricing and Promotions</h3>
        <p>The Service may offer products and services at promotional or discounted rates ("Special Offers"). You acknowledge and agree that:</p>
        <ul>
            <li>These prices are temporary and subject to change at any time without prior notice.</li>
            <li>We reserve the right to revoke discounts and restore original pricing at our sole discretion.</li>
            <li>Any future purchases or renewals will be charged at the then-current price displayed at the time of transaction.</li>
            <li>Changes in pricing will not affect your previously completed purchases or active subscription periods.</li>
        </ul>

        <h3>4.2 Virtual Currency</h3>
        <p>"Fortune Bottles" and "Stars" are virtual goods licensed to you for use within the Service. They have no real-world monetary value and cannot be exchanged for currency.</p>

        <h3>4.2 No Refunds</h3>
        <p>All purchases are final. Because the Service provides immediate access to digital content, you acknowledge that you lose your right of withdrawal once the performance has begun (e.g., bottle consumed, subscription active), to the fullest extent permitted by law.</p>

        <h2>5. Account Termination & "Right to be Forgotten"</h2>
        <h3>5.1 Voluntary Deletion</h3>
        <p>You may delete your account at any time via the <code>/delete_me</code> command.</p>

        <h3>5.2 Consequences of Deletion</h3>
        <div class="notice-box warning">
            <strong>WARNING: Permanent Action</strong><br>
            To prevent abuse and enforce community standards:
            <ul>
                <li><strong>Data Erasure:</strong> Your personal profile and chat history will be permanently deleted.</li>
                <li><strong>Permanent Ban:</strong> Your Telegram ID will be added to a permanent <strong>Blocklist</strong> to prevent re-registration. You will not be able to create a new account with the same Telegram ID.</li>
            </ul>
        </div>

        <h2>6. Disclaimer of Warranties</h2>
        <p>THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.</p>

        <h2>7. Limitation of Liability</h2>
        <p>TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE OPERATOR SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES.</p>

        <h2>8. Indemnification</h2>
        <p>You agree to indemnify and hold harmless the Operator, its affiliates, and their respective officers, directors, employees, and agents from any claims, liabilities, damages, losses, and expenses, including legal fees, arising out of or in any way connected with your access to or use of the Service or your violation of these Terms.</p>

        <h2>9. Governing Law & Dispute Resolution</h2>
        <p>These Terms shall be governed by and construed in accordance with the laws of Taiwan (R.O.C.), without regard to its conflict of law provisions. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the courts located in Taipei, Taiwan.</p>

        <h2>10. Changes to Terms</h2>
        <p>We reserve the right to modify these Terms at any time. Continued use of the Service after any such changes constitutes your acceptance of the new Terms.</p>

        <div class="section-break"></div>
        <p style="text-align: center; color: #999; font-size: 12px;">© 2025 XunNi. All Rights Reserved.</p>
    </div>
</body>
</html>`,
  
  community: `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>XunNi Community Guidelines</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.8;
            color: #333;
            background: #f5f5f5;
            padding: 20px;
        }
        
        .container {
            max-width: 800px;
            margin: 0 auto;
            background: white;
            padding: 40px;
            border-radius: 12px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }
        
        h1 {
            color: #2c3e50;
            font-size: 32px;
            margin-bottom: 10px;
            border-bottom: 3px solid #3498db;
            padding-bottom: 15px;
        }
        
        .version {
            color: #7f8c8d;
            font-size: 14px;
            margin-bottom: 30px;
        }
        
        h2 {
            color: #34495e;
            font-size: 24px;
            margin-top: 40px;
            margin-bottom: 20px;
            border-left: 4px solid #3498db;
            padding-left: 15px;
        }
        
        h3 {
            color: #2c3e50;
            font-size: 18px;
            margin-top: 25px;
            margin-bottom: 15px;
        }
        
        p {
            margin-bottom: 15px;
            text-align: justify;
        }
        
        ul, ol {
            margin-left: 30px;
            margin-bottom: 15px;
        }
        
        li {
            margin-bottom: 10px;
        }
        
        .highlight {
            background: #fff3cd;
            border-left: 4px solid #ffc107;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }
        
        .important {
            background: #f8d7da;
            border-left: 4px solid #dc3545;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }
        
        .success {
            background: #d4edda;
            border-left: 4px solid #28a745;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }
        
        .info {
            background: #d1ecf1;
            border-left: 4px solid #17a2b8;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }
        
        strong {
            color: #2c3e50;
            font-weight: 600;
        }
        
        a {
            color: #3498db;
            text-decoration: none;
        }
        
        a:hover {
            text-decoration: underline;
        }
        
        code {
            background: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
            font-size: 14px;
        }
        
        .emoji {
            font-size: 1.2em;
        }
        
        @media (max-width: 768px) {
            .container {
                padding: 20px;
            }
            
            h1 {
                font-size: 24px;
            }
            
            h2 {
                font-size: 20px;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🤝 XunNi Community Guidelines</h1>
        <p class="version">Last Updated: January 18, 2025 | Version: 1.0</p>
        
        <div class="success">
            <strong>✨ Welcome to XunNi Community!</strong><br>
            XunNi is an anonymous social platform dedicated to creating a safe, friendly, and respectful communication environment. These Community Guidelines will help you understand how to interact with others and build a healthy community together.
        </div>

        <h2>1. Core Values</h2>
        
        <p>XunNi Community is built on the following core values:</p>
        
        <ul>
            <li>💙 <strong>Respect:</strong> Respect every user, regardless of their gender, age, nationality, beliefs, or background</li>
            <li>🛡️ <strong>Safety:</strong> Protect yourself and others from harassment, fraud, and harm</li>
            <li>🤝 <strong>Authenticity:</strong> Maintain honest and genuine communication</li>
            <li>🌈 <strong>Inclusivity:</strong> Accept diversity, no discrimination or exclusion</li>
            <li>🎭 <strong>Privacy:</strong> Respect others' privacy and anonymity choices</li>
        </ul>

        <h2>2. Acceptable Behavior</h2>
        
        <h3>✅ We Encourage</h3>
        <ul>
            <li>💬 <strong>Friendly Communication:</strong> Use polite, warm language</li>
            <li>🎨 <strong>Creative Expression:</strong> Share your thoughts, feelings, and experiences</li>
            <li>🤔 <strong>Meaningful Dialogue:</strong> Engage in deep, valuable conversations</li>
            <li>🌟 <strong>Positive Energy:</strong> Spread positivity and encouragement</li>
            <li>🆘 <strong>Mutual Help:</strong> Offer help and support to others</li>
            <li>🎭 <strong>Respect Anonymity:</strong> Respect others' choice to remain anonymous</li>
        </ul>

        <h3>✅ Good Communication Examples</h3>
        <div class="success">
            <strong>Example 1: Friendly Greeting</strong><br>
            "Hi! I'm an INFP, love reading and music. What about you?"<br><br>
            
            <strong>Example 2: Meaningful Dialogue</strong><br>
            "I've been thinking about the meaning of life lately. What do you think makes life meaningful?"<br><br>
            
            <strong>Example 3: Offering Help</strong><br>
            "You seem a bit down. If you'd like to talk, I'm here to listen."
        </div>

        <h2>3. Prohibited Behavior</h2>
        
        <h3>🚫 Fraud and Financial Activities</h3>
        <div class="important">
            <strong>⚠️ Zero Tolerance for Fraud</strong><br>
            Any form of fraud will result in immediate permanent ban.
        </div>

        <p><strong>Prohibited:</strong></p>
        <ul>
            <li>❌ Requesting money, transfers, loans, or "red envelopes"</li>
            <li>❌ Promoting investments, financial products, cryptocurrencies</li>
            <li>❌ Promoting multi-level marketing (MLM) or Ponzi schemes</li>
            <li>❌ Requesting bank accounts, credit cards, passwords</li>
            <li>❌ Impersonating officials, customer service, or other identities for fraud</li>
            <li>❌ Fabricating stories to solicit donations or sympathy</li>
        </ul>

        <h3>🚫 Harassment and Inappropriate Content</h3>
        <p><strong>Prohibited:</strong></p>
        <ul>
            <li>❌ <strong>Sexual Harassment:</strong> Sending pornographic content, sexual innuendo, or inappropriate advances</li>
            <li>❌ <strong>Verbal Abuse:</strong> Insults, threats, intimidation, or malicious attacks</li>
            <li>❌ <strong>Hate Speech:</strong> Discrimination or attacks based on gender, race, religion, sexual orientation, etc.</li>
            <li>❌ <strong>Stalking:</strong> Repeatedly contacting someone after being blocked or rejected</li>
            <li>❌ <strong>Doxxing:</strong> Disclosing others' personal information without permission</li>
        </ul>

        <h3>🚫 Spam and Abuse</h3>
        <p><strong>Prohibited:</strong></p>
        <ul>
            <li>❌ <strong>Spam:</strong> Repeatedly sending identical or similar content</li>
            <li>❌ <strong>Advertisements:</strong> Promoting products, services, or websites</li>
            <li>❌ <strong>Bots:</strong> Using automated tools or scripts</li>
            <li>❌ <strong>System Abuse:</strong> Maliciously consuming system resources</li>
            <li>❌ <strong>Multiple Accounts:</strong> Creating multiple accounts to evade bans</li>
        </ul>

        <h3>🚫 Illegal and Dangerous Content</h3>
        <p><strong>Prohibited:</strong></p>
        <ul>
            <li>❌ <strong>Illegal Activities:</strong> Drug trafficking, weapons sales, human trafficking, etc.</li>
            <li>❌ <strong>Violent Content:</strong> Gory, horrific, or violent content</li>
            <li>❌ <strong>Child Safety:</strong> Any content involving minors</li>
            <li>❌ <strong>False Information:</strong> Spreading rumors, false news, or misleading information</li>
            <li>❌ <strong>Intellectual Property Infringement:</strong> Piracy, plagiarism, or unauthorized use</li>
        </ul>

        <h2>4. Fraud Prevention Guide</h2>
        
        <div class="important">
            <strong>🚨 Common Fraud Tactics</strong><br>
            Please be vigilant and avoid falling victim to these common scams:
        </div>

        <h3>🎭 Romance Scams</h3>
        <ul>
            <li>⚠️ Quickly expressing affection, claiming "love at first sight"</li>
            <li>⚠️ Fabricating tragic stories (sick family, financial difficulties)</li>
            <li>⚠️ Requesting money or "red envelopes" after establishing trust</li>
            <li>⚠️ Refusing video calls or meetings, always making excuses</li>
        </ul>

        <h3>💰 Investment Scams</h3>
        <ul>
            <li>⚠️ Promising "guaranteed profits" or "get rich quick"</li>
            <li>⚠️ Promoting cryptocurrencies, forex, or investment platforms</li>
            <li>⚠️ Requesting deposits or membership fees</li>
            <li>⚠️ Pressuring immediate decisions, claiming "limited-time offers"</li>
        </ul>

        <h3>🎁 Phishing Scams</h3>
        <ul>
            <li>⚠️ Sending suspicious links claiming "prizes" or "gifts"</li>
            <li>⚠️ Requesting passwords, verification codes, or bank accounts</li>
            <li>⚠️ Impersonating officials or customer service</li>
            <li>⚠️ Claiming account issues requiring "verification"</li>
        </ul>

        <h3>✅ How to Protect Yourself</h3>
        <div class="success">
            <strong>🛡️ Safety Tips:</strong><br>
            1. <strong>Never send money:</strong> XunNi will never ask you for money<br>
            2. <strong>Protect personal information:</strong> Do not disclose real name, address, phone number<br>
            3. <strong>Verify identities:</strong> Be skeptical of strangers' claims<br>
            4. <strong>Report suspicious behavior:</strong> Use <code>/report</code> command immediately<br>
            5. <strong>Trust your instincts:</strong> If something feels wrong, it probably is
        </div>

        <h2>5. Reporting and Blocking</h2>
        
        <h3>📢 How to Report</h3>
        <p>If you encounter violations, please report immediately:</p>
        <ol>
            <li>Use the <code>/report</code> command in conversation</li>
            <li>Select the reason for reporting (harassment, fraud, spam, etc.)</li>
            <li>Provide detailed description and evidence</li>
            <li>We will process within 24-48 hours</li>
        </ol>

        <h3>🚫 How to Block</h3>
        <p>If you don't want to continue communicating with someone:</p>
        <ol>
            <li>Use the <code>/block</code> command in conversation</li>
            <li>The other party will not be able to send you messages</li>
            <li>You will not be matched with them again</li>
            <li>You can unblock anytime</li>
        </ol>

        <h3>⚖️ Reporting Principles</h3>
        <div class="info">
            <strong>📌 Please Note:</strong><br>
            • Reports should be truthful and accurate<br>
            • Do not abuse the reporting system<br>
            • False reports may result in penalties<br>
            • All reports will be kept confidential
        </div>

        <h2>6. Penalties</h2>
        
        <h3>⚠️ Warning</h3>
        <p><strong>Applicable to:</strong></p>
        <ul>
            <li>First minor violation</li>
            <li>Unintentional inappropriate behavior</li>
        </ul>
        <p><strong>Consequence:</strong> Warning message, violation recorded</p>

        <h3>🚫 Temporary Ban</h3>
        <p><strong>Applicable to:</strong></p>
        <ul>
            <li>Repeated minor violations</li>
            <li>Moderate inappropriate behavior</li>
            <li>Spam or abuse</li>
        </ul>
        <p><strong>Consequence:</strong> Account banned for 1-30 days</p>

        <h3>🔒 Permanent Ban</h3>
        <p><strong>Applicable to:</strong></p>
        <ul>
            <li>Serious violations (fraud, harassment, illegal activities)</li>
            <li>Multiple repeated violations</li>
            <li>Threats to community safety</li>
        </ul>
        <p><strong>Consequence:</strong> Account permanently banned, reserve right to legal action</p>

        <h3>🙏 Appeal</h3>
        <p>If you believe a ban was issued in error:</p>
        <ul>
            <li>Use the <code>/appeal</code> command to submit an appeal</li>
            <li>Provide detailed reasons and evidence</li>
            <li>We will review within 3-7 business days</li>
            <li>Appeal decision is final</li>
        </ul>

        <h2>7. Privacy and Anonymity</h2>
        
        <h3>🎭 Respect Anonymity</h3>
        <ul>
            <li>✅ Respect others' choice to remain anonymous</li>
            <li>✅ Do not pressure others to disclose personal information</li>
            <li>✅ Do not attempt to identify or track others</li>
            <li>✅ Do not disclose others' information outside the platform</li>
        </ul>

        <h3>🔒 Protect Your Privacy</h3>
        <div class="highlight">
            <strong>💡 Privacy Protection Tips:</strong><br>
            • Do not disclose real name, address, phone number<br>
            • Do not share social media accounts or photos<br>
            • Do not disclose workplace or school information<br>
            • Be cautious about sharing location information<br>
            • Fully understand the other party before meeting
        </div>

        <h2>8. Healthy Communication Tips</h2>
        
        <h3>💬 How to Start a Good Conversation</h3>
        <ul>
            <li>✅ <strong>Friendly Greeting:</strong> Start with a simple greeting</li>
            <li>✅ <strong>Introduce Yourself:</strong> Share your interests and personality</li>
            <li>✅ <strong>Ask Open Questions:</strong> Encourage the other party to share</li>
            <li>✅ <strong>Listen Actively:</strong> Show genuine interest in the other party</li>
            <li>✅ <strong>Find Common Ground:</strong> Discover shared interests</li>
        </ul>

        <h3>🚫 How to End an Uncomfortable Conversation</h3>
        <ul>
            <li>✅ <strong>Politely Decline:</strong> "Sorry, I don't think we're a good match"</li>
            <li>✅ <strong>Use Block:</strong> Use <code>/block</code> command to end conversation</li>
            <li>✅ <strong>Report Violations:</strong> If the other party violates rules, report immediately</li>
            <li>✅ <strong>Don't Feel Guilty:</strong> You have the right to end any conversation</li>
        </ul>

        <h3>🌟 How to Be a Good Chat Partner</h3>
        <ul>
            <li>✅ <strong>Be Respectful:</strong> Respect others' opinions and feelings</li>
            <li>✅ <strong>Be Patient:</strong> Give the other party time to respond</li>
            <li>✅ <strong>Be Genuine:</strong> Maintain honest and authentic communication</li>
            <li>✅ <strong>Be Positive:</strong> Spread positive energy</li>
            <li>✅ <strong>Be Empathetic:</strong> Try to understand others' perspectives</li>
        </ul>

        <h2>9. Special Situations</h2>
        
        <h3>🆘 If You Encounter Danger</h3>
        <div class="important">
            <strong>⚠️ Emergency Situations</strong><br>
            If you encounter real-world danger or threats:
        </div>
        <ul>
            <li>🚨 <strong>Contact Law Enforcement Immediately:</strong> Dial emergency number (110, 911, etc.)</li>
            <li>🚨 <strong>Ensure Personal Safety:</strong> Leave dangerous environment</li>
            <li>🚨 <strong>Preserve Evidence:</strong> Save chat records and evidence</li>
            <li>🚨 <strong>Report to Platform:</strong> Use <code>/report</code> command to report</li>
        </ul>

        <h3>💔 If You Feel Uncomfortable</h3>
        <ul>
            <li>✅ <strong>Trust Your Feelings:</strong> If something feels wrong, it probably is</li>
            <li>✅ <strong>End Conversation:</strong> You have the right to end any conversation</li>
            <li>✅ <strong>Block User:</strong> Use <code>/block</code> command</li>
            <li>✅ <strong>Seek Support:</strong> Talk to friends or family</li>
        </ul>

        <h3>🤝 If You Witness Violations</h3>
        <ul>
            <li>✅ <strong>Report:</strong> Use <code>/report</code> command</li>
            <li>✅ <strong>Provide Evidence:</strong> Provide detailed information</li>
            <li>✅ <strong>Support Victims:</strong> Offer help and support if possible</li>
            <li>✅ <strong>Do Not Participate:</strong> Do not join in violations</li>
        </ul>

        <h2>10. Community Responsibility</h2>
        
        <div class="success">
            <strong>🌟 Building a Better Community Together</strong><br>
            Every user is an important member of the XunNi community. Your behavior directly affects the community atmosphere and experience.
        </div>

        <h3>👥 Your Responsibility</h3>
        <ul>
            <li>✅ <strong>Follow Guidelines:</strong> Comply with these Community Guidelines</li>
            <li>✅ <strong>Respect Others:</strong> Treat every user with respect</li>
            <li>✅ <strong>Report Violations:</strong> Help maintain community safety</li>
            <li>✅ <strong>Spread Positivity:</strong> Create a friendly communication environment</li>
            <li>✅ <strong>Lead by Example:</strong> Be a role model for others</li>
        </ul>

        <h3>🎯 Our Commitment</h3>
        <ul>
            <li>✅ <strong>Fair Enforcement:</strong> Handle all reports fairly and impartially</li>
            <li>✅ <strong>Transparent Communication:</strong> Clearly explain rules and penalties</li>
            <li>✅ <strong>Continuous Improvement:</strong> Continuously optimize community management</li>
            <li>✅ <strong>User Safety:</strong> Prioritize user safety and privacy</li>
        </ul>

        <h2>11. Contact Us</h2>
        
        <div class="info">
            <strong>📧 For any questions or suggestions, please contact us:</strong><br><br>
            <strong>Telegram:</strong> @xunni_support (Support Bot)<br>
            <strong>Email:</strong> support@xunni.app (if applicable)<br><br>
            We will respond to your request within 7 business days.
        </div>

        <h2>12. Guidelines Updates</h2>
        
        <p>We may update these Community Guidelines from time to time. For significant changes:</p>
        <ul>
            <li>📢 We will send notifications in the Bot</li>
            <li>📢 The update date will be displayed at the top of the page</li>
            <li>📢 Continued use of the service indicates your acceptance of the updated guidelines</li>
        </ul>

        <hr style="margin: 40px 0; border: none; border-top: 1px solid #ddd;">

        <div class="success" style="text-align: center;">
            <strong>✨ Thank you for reading!</strong><br>
            Let's work together to create a safe, friendly, and respectful XunNi community!<br>
            🤝 Respect | 🛡️ Safety | 🌈 Inclusivity | 💙 Authenticity
        </div>

        <hr style="margin: 40px 0; border: none; border-top: 1px solid #ddd;">

        <p style="text-align: center; color: #7f8c8d; font-size: 14px;">
            © 2025 XunNi. All rights reserved.<br>
            <a href="terms.html">Terms of Service</a> | 
            <a href="privacy.html">Privacy Policy</a> | 
            <a href="community.html">Community Guidelines</a>
        </p>
    </div>
</body>
</html>
`,
} as const;

/**
 * Get legal document HTML content
 */
export function getLegalDocument(type: 'privacy' | 'terms' | 'community'): string {
  return LEGAL_DOCUMENTS[type];
}

/**
 * Serve legal document as HTTP response
 */
export function serveLegalDocument(type: 'privacy' | 'terms' | 'community'): Response {
  const content = getLegalDocument(type);
  
  return new Response(content, {
    status: 200,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'public, max-age=3600', // Cache for 1 hour
      'X-Content-Type-Options': 'nosniff',
    },
  });
}
