/**
 * Legal Documents Content
 *
 * This file contains the HTML content of legal documents.
 * Auto-generated from public/*.html files.
 *
 * DO NOT EDIT THIS FILE MANUALLY!
 * Run: node scripts/generate-legal-docs.js
 */

export const LEGAL_DOCUMENTS = {
  privacy: `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>XunNi Privacy Policy</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.8;
            color: #333;
            background: #f5f5f5;
            padding: 20px;
        }
        
        .container {
            max-width: 800px;
            margin: 0 auto;
            background: white;
            padding: 40px;
            border-radius: 12px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }
        
        h1 {
            color: #2c3e50;
            font-size: 32px;
            margin-bottom: 10px;
            border-bottom: 3px solid #3498db;
            padding-bottom: 15px;
        }
        
        .version {
            color: #7f8c8d;
            font-size: 14px;
            margin-bottom: 30px;
        }
        
        h2 {
            color: #34495e;
            font-size: 24px;
            margin-top: 40px;
            margin-bottom: 20px;
            border-left: 4px solid #3498db;
            padding-left: 15px;
        }
        
        h3 {
            color: #2c3e50;
            font-size: 18px;
            margin-top: 25px;
            margin-bottom: 15px;
        }
        
        p {
            margin-bottom: 15px;
            text-align: justify;
        }
        
        ul, ol {
            margin-left: 30px;
            margin-bottom: 15px;
        }
        
        li {
            margin-bottom: 10px;
        }
        
        .highlight {
            background: #fff3cd;
            border-left: 4px solid #ffc107;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }
        
        .important {
            background: #f8d7da;
            border-left: 4px solid #dc3545;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }
        
        .contact {
            background: #d1ecf1;
            border-left: 4px solid #17a2b8;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }
        
        strong {
            color: #2c3e50;
            font-weight: 600;
        }
        
        a {
            color: #3498db;
            text-decoration: none;
        }
        
        a:hover {
            text-decoration: underline;
        }
        
        @media (max-width: 768px) {
            .container {
                padding: 20px;
            }
            
            h1 {
                font-size: 24px;
            }
            
            h2 {
                font-size: 20px;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🔒 XunNi Privacy Policy</h1>
        <p class="version">Last Updated: January 18, 2025 | Version: 1.0</p>
        
        <div class="important">
            <strong>⚠️ Important Notice</strong><br>
            Please read this Privacy Policy carefully. By using XunNi services, you agree to the collection, use, and processing of your personal data as described in this policy. This document is provided in English and shall be the legally binding version.
        </div>

        <h2>1. About This Policy</h2>
        <p>XunNi (hereinafter referred to as "we", "us", or "the Platform") respects and protects the privacy of all users. This Privacy Policy explains how we collect, use, store, and protect your personal data.</p>
        
        <p><strong>Scope of Application:</strong></p>
        <ul>
            <li>XunNi Telegram Bot (@xunnibot)</li>
            <li>XunNi Mini App (if applicable)</li>
            <li>All related services and features</li>
        </ul>

        <h2>2. Information We Collect</h2>
        
        <h3>2.1 Required Information (Collected During Registration)</h3>
        <ul>
            <li><strong>Telegram Basic Information:</strong> Telegram ID, username (if available)</li>
            <li><strong>Personal Information:</strong> Nickname, gender, date of birth (for age verification)</li>
            <li><strong>Psychological Test Results:</strong> MBTI type, zodiac sign</li>
            <li><strong>Security Verification:</strong> Anti-fraud test answers, risk score</li>
        </ul>
        
        <div class="highlight">
            <strong>📌 Why We Need This Information:</strong><br>
            • Gender and date of birth: To match suitable chat partners and ensure users are 18+ years old<br>
            • MBTI and zodiac: To provide more accurate matching services<br>
            • Anti-fraud test: To protect the safety of all users
        </div>

        <h3>2.2 Information Collected During Service Use</h3>
        <ul>
            <li><strong>Usage Records:</strong> Number of bottles thrown/caught, daily quota usage</li>
            <li><strong>Chat Records:</strong> Messages sent and received through bottles</li>
            <li><strong>Interaction Records:</strong> Block, report, and appeal operations</li>
            <li><strong>Invitation Records:</strong> Invitation code usage, number of successful invitations</li>
            <li><strong>VIP Subscription:</strong> Subscription status, expiration date (payment information not included)</li>
        </ul>

        <h3>2.3 Automatically Collected Technical Data</h3>
        <ul>
            <li><strong>Device Information:</strong> Telegram client type, language settings</li>
            <li><strong>Usage Statistics:</strong> Feature usage frequency, active time</li>
            <li><strong>Error Logs:</strong> System errors and exceptions (no personal identifiable information)</li>
        </ul>

        <h3>2.4 Information We Do NOT Collect</h3>
        <ul>
            <li>❌ Real name, ID card number</li>
            <li>❌ Phone number, email address (unless voluntarily provided)</li>
            <li>❌ Payment card numbers, bank account information</li>
            <li>❌ Precise geolocation</li>
            <li>❌ Device IMEI, MAC address</li>
        </ul>

        <h2>3. How We Use Your Information</h2>
        
        <h3>3.1 Providing Core Services</h3>
        <ul>
            <li>✅ Matching suitable chat partners (based on gender, age, MBTI, zodiac)</li>
            <li>✅ Managing daily quotas and VIP privileges</li>
            <li>✅ Processing invitation rewards</li>
            <li>✅ Providing language translation services (VIP users)</li>
        </ul>

        <h3>3.2 Security and Risk Control</h3>
        <ul>
            <li>🛡️ Verifying user age (ensuring 18+ years old)</li>
            <li>🛡️ Detecting and preventing fraud</li>
            <li>🛡️ Processing reports and appeals</li>
            <li>🛡️ Executing bans and unbans</li>
        </ul>

        <h3>3.3 Service Quality Improvement</h3>
        <ul>
            <li>📊 Analyzing usage trends and user behavior</li>
            <li>📊 Optimizing matching algorithms</li>
            <li>📊 Improving feature design</li>
            <li>📊 Fixing bugs and improving performance</li>
        </ul>

        <h3>3.4 Notifications and Push Messages</h3>
        <ul>
            <li>📬 Sending new message notifications</li>
            <li>📬 Pushing weekly horoscope updates</li>
            <li>📬 Sending system announcements and important updates</li>
        </ul>

        <h2>4. Information Sharing and Disclosure</h2>
        
        <div class="important">
            <strong>🔒 We Do NOT Sell Your Personal Data</strong><br>
            We commit to never selling your personal data to third parties.
        </div>

        <h3>4.1 Service Providers</h3>
        <p>We may share necessary data with the following service providers:</p>
        <ul>
            <li><strong>Cloudflare:</strong> Cloud computing and database services (data stored in Cloudflare D1)</li>
            <li><strong>OpenAI / Google Translate:</strong> Translation services (VIP users only, message content only)</li>
            <li><strong>Telegram:</strong> Message delivery service</li>
        </ul>
        
        <p><strong>Data Protection Measures:</strong></p>
        <ul>
            <li>✅ All service providers sign data protection agreements</li>
            <li>✅ Only minimum necessary data is shared</li>
            <li>✅ Encrypted transmission (HTTPS/TLS)</li>
        </ul>

        <h3>4.2 Legal Requirements</h3>
        <p>We may be required to disclose your data in the following situations:</p>
        <ul>
            <li>⚖️ Compliance with laws, regulations, or court orders</li>
            <li>⚖️ Response to lawful requests from government authorities</li>
            <li>⚖️ Protection of our rights, property, or safety</li>
            <li>⚖️ Prevention of fraud, abuse, or illegal activities</li>
        </ul>

        <h3>4.3 Anonymous Statistical Data</h3>
        <p>We may publicly share or disclose anonymous statistical data, such as:</p>
        <ul>
            <li>📊 Total users, active users</li>
            <li>📊 Total bottles, matching success rate</li>
            <li>📊 MBTI type distribution, zodiac distribution</li>
        </ul>
        <p><strong>This data does not contain any personally identifiable information.</strong></p>

        <h2>5. Data Protection Measures</h2>
        
        <h3>5.1 Technical Protection</h3>
        <ul>
            <li>🔐 <strong>Encrypted Transmission:</strong> All data transmission uses HTTPS/TLS encryption</li>
            <li>🔐 <strong>Access Control:</strong> Strict limitation of database access permissions</li>
            <li>🔐 <strong>Anonymous Forwarding:</strong> Chat messages forwarded through relay bot, not exposing real Telegram ID</li>
            <li>🔐 <strong>Data Isolation:</strong> Different users' data is isolated from each other</li>
        </ul>

        <h3>5.2 Administrative Protection</h3>
        <ul>
            <li>👥 <strong>Principle of Least Privilege:</strong> Only authorized personnel can access necessary data</li>
            <li>👥 <strong>Operation Audit:</strong> All administrator operations are logged</li>
            <li>👥 <strong>Regular Review:</strong> Regular inspection of security measures and access logs</li>
        </ul>

        <h3>5.3 Anonymity Protection</h3>
        <ul>
            <li>🎭 <strong>Nickname Masking:</strong> Partial masking of nicknames in certain scenarios</li>
            <li>🎭 <strong>Anonymous Chat:</strong> Chat partners cannot directly obtain your Telegram ID</li>
            <li>🎭 <strong>Selective Disclosure:</strong> You can choose whether to disclose personal information</li>
        </ul>

        <h2>6. Data Retention and Deletion</h2>
        
        <h3>6.1 Data Retention Period</h3>
        <ul>
            <li><strong>Personal Data:</strong> During account existence</li>
            <li><strong>Bottles:</strong> Soft-deleted after 90 days (marked as deleted, no longer displayed)</li>
            <li><strong>Chat Records:</strong>
                <ul>
                    <li><strong>VIP Users:</strong> Retained for 3 years</li>
                    <li><strong>Free Users:</strong> Retained for 1 year</li>
                </ul>
            </li>
            <li><strong>Security Audit Records:</strong> Retained for 90 days after account deletion (for security review only)</li>
        </ul>

        <h3>6.2 Account Deletion</h3>
        <p>You can delete your account at any time using the <code>/delete_me</code> command. After deletion:</p>
        <ul>
            <li>✅ Your personal data will be permanently deleted</li>
            <li>✅ Your bottles and chat records will be deleted</li>
            <li>✅ Your invitation records will be deleted</li>
            <li>⚠️ Security audit records will be retained for 90 days (to prevent abuse)</li>
            <li>⚠️ Deletion is irreversible</li>
        </ul>

        <div class="highlight">
            <strong>📌 Reason for Retaining Security Audit Records:</strong><br>
            To prevent malicious users from deleting accounts to evade bans and re-registering, we retain minimal security audit information (such as ban records, report records) for 90 days. These records are used for security purposes only and will not be used for other purposes.
        </div>

        <h2>7. Your Rights</h2>
        
        <h3>7.1 Right of Access</h3>
        <p>You have the right to view and access your personal data at any time:</p>
        <ul>
            <li>Use <code>/profile</code> to view personal information</li>
            <li>Use <code>/stats</code> to view usage statistics</li>
        </ul>

        <h3>7.2 Right to Rectification</h3>
        <p>You can modify the following data:</p>
        <ul>
            <li>✅ Nickname (use <code>/profile</code>)</li>
            <li>✅ MBTI type (use <code>/profile</code>)</li>
            <li>✅ Language preference</li>
            <li>❌ Gender and date of birth (cannot be modified after setting, to ensure data authenticity)</li>
        </ul>

        <h3>7.3 Right to Erasure</h3>
        <p>You have the right to delete your account and data at any time (use <code>/delete_me</code>).</p>

        <h3>7.4 Right to Object</h3>
        <p>You have the right to object to certain data processing methods:</p>
        <ul>
            <li>Stop receiving horoscope push notifications</li>
            <li>Stop receiving system notifications (except for certain notifications)</li>
        </ul>

        <h3>7.5 Right to Data Portability</h3>
        <p>You have the right to request that we provide your personal data in a structured, commonly used format. Please contact us to make a request.</p>

        <h2>8. Children's Privacy Protection</h2>
        
        <div class="important">
            <strong>⚠️ Age Restriction: 18+ Years Old</strong><br>
            XunNi services are only available to adults aged 18 and above. We do not knowingly collect personal data from children under 18 years old.
        </div>

        <p><strong>Age Verification Measures:</strong></p>
        <ul>
            <li>✅ Date of birth must be provided during registration</li>
            <li>✅ System automatically verifies age</li>
            <li>✅ Users under 18 will be refused registration</li>
        </ul>

        <p><strong>If you discover a minor using this service:</strong></p>
        <p>Please contact us immediately, and we will immediately delete the account and all related data.</p>

        <h2>9. Cookies and Tracking Technologies</h2>
        
        <p>XunNi Telegram Bot itself does not use cookies. However, we may use the following technologies:</p>
        <ul>
            <li><strong>Cloudflare Analytics:</strong> Anonymous usage statistics (no personal identifiable information)</li>
            <li><strong>Telegram initData:</strong> Verify Mini App user identity (only used in Mini App)</li>
        </ul>

        <h2>10. International Data Transfers</h2>
        
        <p>Your data may be transferred to locations outside your country/region:</p>
        <ul>
            <li><strong>Cloudflare D1:</strong> Data stored in Cloudflare global data centers</li>
            <li><strong>Translation Services:</strong> Message content may be sent to OpenAI or Google servers (VIP users only)</li>
        </ul>

        <p><strong>Data Protection Measures:</strong></p>
        <ul>
            <li>✅ All data transfers use encryption</li>
            <li>✅ Service providers comply with GDPR and other data protection regulations</li>
            <li>✅ Standard Contractual Clauses (SCC) signed</li>
        </ul>

        <h2>11. Policy Updates</h2>
        
        <p>We may update this Privacy Policy from time to time. For significant changes:</p>
        <ul>
            <li>📢 We will send notifications in the Bot</li>
            <li>📢 The update date will be displayed at the top of the page</li>
            <li>📢 You can choose to continue using or delete your account</li>
        </ul>

        <p><strong>Continued use of the service indicates your acceptance of the updated policy.</strong></p>

        <h2>12. Contact Us</h2>
        
        <div class="contact">
            <strong>📧 For any privacy-related questions, please contact us:</strong><br><br>
            <strong>Telegram:</strong> @xunni_support (Support Bot)<br>
            <strong>Email:</strong> privacy@xunni.app (if applicable)<br><br>
            We will respond to your request within 7 business days.
        </div>

        <h2>13. Governing Law</h2>
        
        <p>This Privacy Policy is governed by the following laws:</p>
        <ul>
            <li>European Union General Data Protection Regulation (GDPR)</li>
            <li>California Consumer Privacy Act (CCPA)</li>
            <li>Taiwan Personal Data Protection Act</li>
            <li>Other applicable data protection laws</li>
        </ul>

        <hr style="margin: 40px 0; border: none; border-top: 1px solid #ddd;">

        <p style="text-align: center; color: #7f8c8d; font-size: 14px;">
            © 2025 XunNi. All rights reserved.<br>
            <a href="terms.html">Terms of Service</a> | 
            <a href="privacy.html">Privacy Policy</a> | 
            <a href="community.html">Community Guidelines</a>
        </p>
    </div>
</body>
</html>
`,

  terms: `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>XunNi Terms of Service</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.8;
            color: #333;
            background: #f5f5f5;
            padding: 20px;
        }
        
        .container {
            max-width: 800px;
            margin: 0 auto;
            background: white;
            padding: 40px;
            border-radius: 12px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }
        
        h1 {
            color: #2c3e50;
            font-size: 32px;
            margin-bottom: 10px;
            border-bottom: 3px solid #3498db;
            padding-bottom: 15px;
        }
        
        .version {
            color: #7f8c8d;
            font-size: 14px;
            margin-bottom: 30px;
        }
        
        h2 {
            color: #34495e;
            font-size: 24px;
            margin-top: 40px;
            margin-bottom: 20px;
            border-left: 4px solid #3498db;
            padding-left: 15px;
        }
        
        h3 {
            color: #2c3e50;
            font-size: 18px;
            margin-top: 25px;
            margin-bottom: 15px;
        }
        
        h4 {
            color: #2c3e50;
            font-size: 16px;
            margin-top: 20px;
            margin-bottom: 10px;
        }
        
        p {
            margin-bottom: 15px;
            text-align: justify;
        }
        
        ul, ol {
            margin-left: 30px;
            margin-bottom: 15px;
        }
        
        li {
            margin-bottom: 10px;
        }
        
        .highlight {
            background: #fff3cd;
            border-left: 4px solid #ffc107;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }
        
        .important {
            background: #f8d7da;
            border-left: 4px solid #dc3545;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }
        
        .success {
            background: #d4edda;
            border-left: 4px solid #28a745;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }
        
        .contact {
            background: #d1ecf1;
            border-left: 4px solid #17a2b8;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }
        
        strong {
            color: #2c3e50;
            font-weight: 600;
        }
        
        a {
            color: #3498db;
            text-decoration: none;
        }
        
        a:hover {
            text-decoration: underline;
        }
        
        code {
            background: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
            font-size: 14px;
        }
        
        @media (max-width: 768px) {
            .container {
                padding: 20px;
            }
            
            h1 {
                font-size: 24px;
            }
            
            h2 {
                font-size: 20px;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>📜 XunNi Terms of Service</h1>
        <p class="version">Last Updated: January 18, 2025 | Version: 1.0</p>
        
        <div class="important">
            <strong>⚠️ Important Notice</strong><br>
            Please read these Terms of Service carefully. By using XunNi services, you agree to comply with all provisions of these Terms. If you do not agree to these Terms, please do not use this service. <strong>This English version is the legally binding version.</strong>
        </div>

        <h2>1. Service Description</h2>
        
        <h3>1.1 Service Content</h3>
        <p>XunNi is a Telegram-based anonymous bottle messaging platform that provides the following services:</p>
        <ul>
            <li>🍾 <strong>Bottle Matching:</strong> Match chat partners based on MBTI, zodiac, gender, age, and other criteria</li>
            <li>💬 <strong>Anonymous Chat:</strong> Anonymous conversations through relay bot to protect privacy</li>
            <li>🧪 <strong>Psychological Tests:</strong> MBTI personality test, horoscope readings</li>
            <li>🌐 <strong>Language Translation:</strong> VIP users can use automatic translation in 34 languages</li>
            <li>👥 <strong>Invitation Rewards:</strong> Invite friends to increase daily quota</li>
        </ul>

        <h3>1.2 Nature of Service</h3>
        <div class="highlight">
            <strong>📌 XunNi is a social platform, NOT:</strong><br>
            ❌ A dating or matrimonial service<br>
            ❌ A financial or investment platform<br>
            ❌ A commercial trading platform<br>
            ❌ An adult or pornographic content platform
        </div>

        <h2>2. Eligibility</h2>
        
        <h3>2.1 Age Restriction</h3>
        <div class="important">
            <strong>⚠️ Must Be 18+ Years Old</strong><br>
            You must be at least 18 years old to use XunNi services. You must provide your real date of birth during registration, and the system will automatically verify your age.
        </div>

        <h3>2.2 Account Requirements</h3>
        <ul>
            <li>✅ Must have a valid Telegram account</li>
            <li>✅ Each Telegram account can only register one XunNi account</li>
            <li>✅ Must provide real gender and date of birth (cannot be modified after setting)</li>
            <li>✅ Must complete anti-fraud security test</li>
        </ul>

        <h3>2.3 Prohibited Use</h3>
        <p>The following persons are prohibited from using XunNi services:</p>
        <ul>
            <li>❌ Minors under 18 years old</li>
            <li>❌ Users previously permanently banned for violations</li>
            <li>❌ Users using false identities or impersonating others</li>
            <li>❌ Persons legally prohibited from using social services</li>
        </ul>

        <h2>3. Usage Rules</h2>
        
        <h3>3.1 Prohibited Conduct</h3>
        <p>When using XunNi services, you must not engage in the following conduct:</p>

        <h4>🚫 Fraud and Financial Activities</h4>
        <ul>
            <li>❌ Any form of fraud, deception, or misleading behavior</li>
            <li>❌ Requesting or providing money, transfers, loans</li>
            <li>❌ Promoting investments, financial products, cryptocurrencies</li>
            <li>❌ Promoting multi-level marketing (MLM) or Ponzi schemes</li>
            <li>❌ Requesting bank accounts, credit card numbers, passwords, or other sensitive information</li>
        </ul>

        <h4>🚫 Harassment and Inappropriate Content</h4>
        <ul>
            <li>❌ Sending pornographic, obscene, or sexually explicit content</li>
            <li>❌ Sexual harassment, sexual innuendo, or inappropriate advances</li>
            <li>❌ Insults, threats, or intimidation</li>
            <li>❌ Hate speech or discriminatory content</li>
            <li>❌ Violent, gory, or horrific content</li>
        </ul>

        <h4>🚫 Spam and Abuse</h4>
        <ul>
            <li>❌ Sending spam, advertisements, or promotions</li>
            <li>❌ Repeatedly sending identical or similar content</li>
            <li>❌ Using bots or automated tools</li>
            <li>❌ Maliciously consuming system resources</li>
        </ul>

        <h4>🚫 Illegal and Dangerous Behavior</h4>
        <ul>
            <li>❌ Engaging in any illegal or criminal activities</li>
            <li>❌ Selling drugs, weapons, or prohibited items</li>
            <li>❌ Violating others' privacy, portrait rights, or intellectual property rights</li>
            <li>❌ Spreading false information or rumors</li>
            <li>❌ Inciting or assisting others in illegal activities</li>
        </ul>

        <h3>3.2 Content Guidelines</h3>
        <p>All content you send must comply with the following guidelines:</p>
        <ul>
            <li>✅ <strong>Text and Official Emojis Only:</strong> Images, videos, and files are not supported</li>
            <li>✅ <strong>URL Whitelist:</strong> Only whitelisted URLs are allowed (e.g., Wikipedia, YouTube)</li>
            <li>✅ <strong>Respect Others:</strong> Maintain polite, friendly, and respectful communication</li>
            <li>✅ <strong>Authentic Communication:</strong> Do not impersonate others or use false identities</li>
        </ul>

        <h3>3.3 Quotas and Limits</h3>
        <p><strong>Free Users:</strong></p>
        <ul>
            <li>Daily base quota: 3 bottles</li>
            <li>Invitation reward: +1 permanent quota per successful invitation (max 10)</li>
            <li>Ad reward: Watch up to 20 ads per day, +1 temporary quota each</li>
            <li>Maximum quota: 10 (base+invitation) + 20 (ads) = 30 bottles/day</li>
        </ul>

        <p><strong>VIP Users:</strong></p>
        <ul>
            <li>Daily base quota: 30 bottles</li>
            <li>Invitation reward: +1 permanent quota per successful invitation (max 100)</li>
            <li>No ads</li>
            <li>Automatic translation in 34 languages</li>
            <li>Advanced filtering (zodiac, MBTI)</li>
        </ul>

        <h2>4. Platform Disclaimers</h2>
        
        <div class="important">
            <strong>⚠️ Important Disclaimer</strong><br>
            XunNi is an anonymous social platform. We cannot fully control user behavior. You assume all risks when using this service.
        </div>

        <h3>4.1 User Content Disclaimer</h3>
        <p>XunNi is not responsible for:</p>
        <ul>
            <li>❌ Message content sent by users (including but not limited to text, links)</li>
            <li>❌ Interactions, disputes, or conflicts between users</li>
            <li>❌ Authenticity or accuracy of personal information provided by users</li>
            <li>❌ User behavior and transactions outside the platform</li>
        </ul>

        <h3>4.2 Fraud and Financial Disclaimer</h3>
        <div class="important">
            <strong>🚨 Fraud Warning</strong><br>
            • XunNi will NEVER ask you for money, transfers, or personal financial information<br>
            • Any messages requesting money or investments may be scams<br>
            • Do not believe any "get rich quick" or "investment opportunities" promises<br>
            • If you encounter fraud, report immediately and contact law enforcement
        </div>

        <p><strong>The Platform is NOT responsible for:</strong></p>
        <ul>
            <li>❌ Financial losses caused by fraud or deception</li>
            <li>❌ Any financial transactions or investment activities by users</li>
            <li>❌ Losses caused by disclosure of personal information</li>
            <li>❌ Any transactions conducted outside the platform</li>
        </ul>

        <h3>4.3 Service Availability Disclaimer</h3>
        <p>XunNi does not guarantee the following aspects of the service:</p>
        <ul>
            <li>❌ Service will be uninterrupted or error-free</li>
            <li>❌ All features will always be available</li>
            <li>❌ Data will not be lost or corrupted</li>
            <li>❌ Matching results will meet your expectations</li>
        </ul>

        <h3>4.4 Third-Party Service Disclaimer</h3>
        <p>XunNi uses the following third-party services, for which we are not responsible:</p>
        <ul>
            <li>Telegram platform (message delivery)</li>
            <li>OpenAI / Google Translate (translation services)</li>
            <li>Cloudflare (cloud computing)</li>
            <li>GigaPub (advertising services)</li>
        </ul>

        <h3>4.5 Health and Safety Disclaimer</h3>
        <div class="highlight">
            <strong>⚠️ Online Dating Safety Tips</strong><br>
            • Protect personal privacy, do not disclose real name, address, phone number<br>
            • Do not easily trust strangers<br>
            • Fully understand the other party before meeting, choose public places<br>
            • Inform friends or family of your whereabouts<br>
            • If in danger, contact law enforcement immediately
        </div>

        <p><strong>The Platform is NOT responsible for:</strong></p>
        <ul>
            <li>❌ Safety of offline meetings between users</li>
            <li>❌ Physical or mental health of users</li>
            <li>❌ Personal injury or property damage between users</li>
        </ul>

        <h2>5. Violation Handling</h2>
        
        <h3>5.1 Reporting Mechanism</h3>
        <p>If you discover violations, please report using the following methods:</p>
        <ul>
            <li>📢 Use the <code>/report</code> command in conversation</li>
            <li>📢 Provide detailed evidence and description of violations</li>
            <li>📢 We will process within 24-48 hours</li>
        </ul>

        <h3>5.2 Penalties</h3>
        <p>Depending on the severity of violations, we may take the following measures:</p>

        <h4>⚠️ Minor Violations (Warning)</h4>
        <ul>
            <li>First minor violation</li>
            <li>Send warning message</li>
            <li>Record violation</li>
        </ul>

        <h4>🚫 Moderate Violations (Temporary Ban)</h4>
        <ul>
            <li>Repeated minor violations</li>
            <li>Moderate inappropriate behavior</li>
            <li>Ban for 1-30 days</li>
        </ul>

        <h4>🔒 Severe Violations (Permanent Ban)</h4>
        <ul>
            <li>Serious violations (fraud, harassment, illegal activities)</li>
            <li>Multiple repeated violations</li>
            <li>Permanent account ban</li>
            <li>Reserve right to legal action</li>
        </ul>

        <h3>5.3 Appeal Mechanism</h3>
        <p>If you believe a ban was issued in error, you can appeal:</p>
        <ul>
            <li>Use the <code>/appeal</code> command to submit an appeal</li>
            <li>Provide detailed reasons and evidence for appeal</li>
            <li>We will review within 3-7 business days</li>
            <li>Appeal decision is final</li>
        </ul>

        <h2>6. Intellectual Property</h2>
        
        <h3>6.1 Platform Content</h3>
        <p>The following XunNi content is protected by intellectual property rights:</p>
        <ul>
            <li>© Platform name, logo, trademarks</li>
            <li>© Software code, algorithms</li>
            <li>© MBTI test questions and result analysis</li>
            <li>© Horoscope content</li>
            <li>© Interface design, copywriting</li>
        </ul>

        <p><strong>Without authorization, you may NOT:</strong></p>
        <ul>
            <li>❌ Copy, modify, or distribute platform content</li>
            <li>❌ Reverse engineer or decompile software</li>
            <li>❌ Use platform name or logo</li>
            <li>❌ Create similar or competitive services</li>
        </ul>

        <h3>6.2 User Content</h3>
        <p>Content you send (messages, nicknames, etc.) remains yours, but you grant XunNi:</p>
        <ul>
            <li>✅ The right to store and process your content</li>
            <li>✅ The right to use your content to provide services</li>
            <li>✅ The right to analyze your content to improve services (anonymized)</li>
        </ul>

        <h2>7. VIP Subscription</h2>
        
        <h3>7.1 Subscription Details</h3>
        <ul>
            <li>💎 VIP subscription is paid through Telegram Stars</li>
            <li>💎 Subscription fee: approximately 5 USD / month</li>
            <li>💎 Auto-renewal, can be canceled anytime</li>
            <li>💎 After cancellation, VIP privileges continue until subscription period ends</li>
        </ul>

        <h3>7.2 Refund Policy</h3>
        <div class="important">
            <strong>⚠️ No Refunds</strong><br>
            As VIP subscription is a digital service, refunds are not available once purchased. Please consider carefully before purchasing.
        </div>

        <p><strong>Exceptions:</strong></p>
        <ul>
            <li>✅ Technical failures preventing service use</li>
            <li>✅ Platform billing errors</li>
            <li>✅ Other situations where the platform is at fault</li>
        </ul>

        <h3>7.3 Service Changes</h3>
        <p>We reserve the right to:</p>
        <ul>
            <li>Adjust VIP features and privileges</li>
            <li>Adjust subscription prices (existing subscriptions unaffected)</li>
            <li>Terminate VIP service (30 days advance notice)</li>
        </ul>

        <h2>8. Service Changes and Termination</h2>
        
        <h3>8.1 Service Changes</h3>
        <p>XunNi reserves the right to:</p>
        <ul>
            <li>Modify, suspend, or terminate part or all of the service at any time</li>
            <li>Adjust features, quotas, rules</li>
            <li>Update these Terms of Service</li>
        </ul>

        <p><strong>For significant changes, we will:</strong></p>
        <ul>
            <li>📢 Provide 7-30 days advance notice</li>
            <li>📢 Send announcements in the Bot</li>
            <li>📢 Give you the option to continue using or delete your account</li>
        </ul>

        <h3>8.2 Service Termination</h3>
        <p>We may terminate your account in the following situations:</p>
        <ul>
            <li>You seriously violate these Terms</li>
            <li>Your account is permanently banned</li>
            <li>You request account deletion (<code>/delete_me</code>)</li>
            <li>You are inactive for an extended period (over 1 year)</li>
        </ul>

        <h2>9. Limitation of Liability</h2>
        
        <div class="important">
            <strong>⚠️ Limitation of Liability</strong><br>
            To the maximum extent permitted by law, XunNi and its operators, employees, and partners are NOT liable for:
        </div>

        <ul>
            <li>❌ Any indirect, incidental, special, or punitive damages</li>
            <li>❌ Loss of profits, goodwill, or data</li>
            <li>❌ Service interruptions, errors, or delays</li>
            <li>❌ Losses caused by third-party actions</li>
            <li>❌ Disputes and losses between users</li>
        </ul>

        <p><strong>Maximum Liability:</strong></p>
        <p>In any event, XunNi's total liability shall not exceed the subscription fees you paid in the past 12 months (if any).</p>

        <h2>10. Dispute Resolution</h2>
        
        <h3>10.1 Amicable Negotiation</h3>
        <p>If disputes arise, please contact us first to attempt amicable resolution:</p>
        <div class="contact">
            <strong>📧 Contact Information:</strong><br>
            Telegram: @xunni_support<br>
            Email: support@xunni.app (if applicable)
        </div>

        <h3>10.2 Governing Law</h3>
        <p>These Terms are governed by:</p>
        <ul>
            <li>Taiwan law (if applicable)</li>
            <li>International laws commonly applicable to internet services</li>
        </ul>

        <h3>10.3 Jurisdiction</h3>
        <p>If amicable resolution is not possible, both parties agree that the Taipei District Court of Taiwan shall be the court of first instance jurisdiction (if applicable).</p>

        <h2>11. Miscellaneous</h2>
        
        <h3>11.1 Entire Agreement</h3>
        <p>These Terms of Service, Privacy Policy, and Community Guidelines constitute the entire agreement between you and XunNi.</p>

        <h3>11.2 Severability</h3>
        <p>If any provision of these Terms is deemed invalid or unenforceable, the remaining provisions shall remain in effect.</p>

        <h3>11.3 No Waiver</h3>
        <p>XunNi's failure to exercise or delay in exercising any right does not constitute a waiver of that right.</p>

        <h3>11.4 Assignment</h3>
        <p>You may not assign your rights or obligations under these Terms without XunNi's consent. XunNi may freely assign these Terms.</p>

        <h2>12. Contact Us</h2>
        
        <div class="contact">
            <strong>📧 For any questions, please contact us:</strong><br><br>
            <strong>Telegram:</strong> @xunni_support (Support Bot)<br>
            <strong>Email:</strong> support@xunni.app (if applicable)<br><br>
            We will respond to your request within 7 business days.
        </div>

        <h2>13. Acceptance of Terms</h2>
        
        <div class="success">
            <strong>✅ By using XunNi services, you acknowledge that you have read, understood, and agree to:</strong><br>
            • These Terms of Service<br>
            • Privacy Policy<br>
            • Community Guidelines<br>
            • All related rules and policies
        </div>

        <p><strong>If you do not agree to these Terms, please do not use XunNi services.</strong></p>

        <hr style="margin: 40px 0; border: none; border-top: 1px solid #ddd;">

        <p style="text-align: center; color: #7f8c8d; font-size: 14px;">
            © 2025 XunNi. All rights reserved.<br>
            <a href="terms.html">Terms of Service</a> | 
            <a href="privacy.html">Privacy Policy</a> | 
            <a href="community.html">Community Guidelines</a>
        </p>
    </div>
</body>
</html>
`,

  community: `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>XunNi Community Guidelines</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
            line-height: 1.8;
            color: #333;
            background: #f5f5f5;
            padding: 20px;
        }
        
        .container {
            max-width: 800px;
            margin: 0 auto;
            background: white;
            padding: 40px;
            border-radius: 12px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }
        
        h1 {
            color: #2c3e50;
            font-size: 32px;
            margin-bottom: 10px;
            border-bottom: 3px solid #3498db;
            padding-bottom: 15px;
        }
        
        .version {
            color: #7f8c8d;
            font-size: 14px;
            margin-bottom: 30px;
        }
        
        h2 {
            color: #34495e;
            font-size: 24px;
            margin-top: 40px;
            margin-bottom: 20px;
            border-left: 4px solid #3498db;
            padding-left: 15px;
        }
        
        h3 {
            color: #2c3e50;
            font-size: 18px;
            margin-top: 25px;
            margin-bottom: 15px;
        }
        
        p {
            margin-bottom: 15px;
            text-align: justify;
        }
        
        ul, ol {
            margin-left: 30px;
            margin-bottom: 15px;
        }
        
        li {
            margin-bottom: 10px;
        }
        
        .highlight {
            background: #fff3cd;
            border-left: 4px solid #ffc107;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }
        
        .important {
            background: #f8d7da;
            border-left: 4px solid #dc3545;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }
        
        .success {
            background: #d4edda;
            border-left: 4px solid #28a745;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }
        
        .info {
            background: #d1ecf1;
            border-left: 4px solid #17a2b8;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }
        
        strong {
            color: #2c3e50;
            font-weight: 600;
        }
        
        a {
            color: #3498db;
            text-decoration: none;
        }
        
        a:hover {
            text-decoration: underline;
        }
        
        code {
            background: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
            font-size: 14px;
        }
        
        .emoji {
            font-size: 1.2em;
        }
        
        @media (max-width: 768px) {
            .container {
                padding: 20px;
            }
            
            h1 {
                font-size: 24px;
            }
            
            h2 {
                font-size: 20px;
            }
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>🤝 XunNi Community Guidelines</h1>
        <p class="version">Last Updated: January 18, 2025 | Version: 1.0</p>
        
        <div class="success">
            <strong>✨ Welcome to XunNi Community!</strong><br>
            XunNi is an anonymous social platform dedicated to creating a safe, friendly, and respectful communication environment. These Community Guidelines will help you understand how to interact with others and build a healthy community together.
        </div>

        <h2>1. Core Values</h2>
        
        <p>XunNi Community is built on the following core values:</p>
        
        <ul>
            <li>💙 <strong>Respect:</strong> Respect every user, regardless of their gender, age, nationality, beliefs, or background</li>
            <li>🛡️ <strong>Safety:</strong> Protect yourself and others from harassment, fraud, and harm</li>
            <li>🤝 <strong>Authenticity:</strong> Maintain honest and genuine communication</li>
            <li>🌈 <strong>Inclusivity:</strong> Accept diversity, no discrimination or exclusion</li>
            <li>🎭 <strong>Privacy:</strong> Respect others' privacy and anonymity choices</li>
        </ul>

        <h2>2. Acceptable Behavior</h2>
        
        <h3>✅ We Encourage</h3>
        <ul>
            <li>💬 <strong>Friendly Communication:</strong> Use polite, warm language</li>
            <li>🎨 <strong>Creative Expression:</strong> Share your thoughts, feelings, and experiences</li>
            <li>🤔 <strong>Meaningful Dialogue:</strong> Engage in deep, valuable conversations</li>
            <li>🌟 <strong>Positive Energy:</strong> Spread positivity and encouragement</li>
            <li>🆘 <strong>Mutual Help:</strong> Offer help and support to others</li>
            <li>🎭 <strong>Respect Anonymity:</strong> Respect others' choice to remain anonymous</li>
        </ul>

        <h3>✅ Good Communication Examples</h3>
        <div class="success">
            <strong>Example 1: Friendly Greeting</strong><br>
            "Hi! I'm an INFP, love reading and music. What about you?"<br><br>
            
            <strong>Example 2: Meaningful Dialogue</strong><br>
            "I've been thinking about the meaning of life lately. What do you think makes life meaningful?"<br><br>
            
            <strong>Example 3: Offering Help</strong><br>
            "You seem a bit down. If you'd like to talk, I'm here to listen."
        </div>

        <h2>3. Prohibited Behavior</h2>
        
        <h3>🚫 Fraud and Financial Activities</h3>
        <div class="important">
            <strong>⚠️ Zero Tolerance for Fraud</strong><br>
            Any form of fraud will result in immediate permanent ban.
        </div>

        <p><strong>Prohibited:</strong></p>
        <ul>
            <li>❌ Requesting money, transfers, loans, or "red envelopes"</li>
            <li>❌ Promoting investments, financial products, cryptocurrencies</li>
            <li>❌ Promoting multi-level marketing (MLM) or Ponzi schemes</li>
            <li>❌ Requesting bank accounts, credit cards, passwords</li>
            <li>❌ Impersonating officials, customer service, or other identities for fraud</li>
            <li>❌ Fabricating stories to solicit donations or sympathy</li>
        </ul>

        <h3>🚫 Harassment and Inappropriate Content</h3>
        <p><strong>Prohibited:</strong></p>
        <ul>
            <li>❌ <strong>Sexual Harassment:</strong> Sending pornographic content, sexual innuendo, or inappropriate advances</li>
            <li>❌ <strong>Verbal Abuse:</strong> Insults, threats, intimidation, or malicious attacks</li>
            <li>❌ <strong>Hate Speech:</strong> Discrimination or attacks based on gender, race, religion, sexual orientation, etc.</li>
            <li>❌ <strong>Stalking:</strong> Repeatedly contacting someone after being blocked or rejected</li>
            <li>❌ <strong>Doxxing:</strong> Disclosing others' personal information without permission</li>
        </ul>

        <h3>🚫 Spam and Abuse</h3>
        <p><strong>Prohibited:</strong></p>
        <ul>
            <li>❌ <strong>Spam:</strong> Repeatedly sending identical or similar content</li>
            <li>❌ <strong>Advertisements:</strong> Promoting products, services, or websites</li>
            <li>❌ <strong>Bots:</strong> Using automated tools or scripts</li>
            <li>❌ <strong>System Abuse:</strong> Maliciously consuming system resources</li>
            <li>❌ <strong>Multiple Accounts:</strong> Creating multiple accounts to evade bans</li>
        </ul>

        <h3>🚫 Illegal and Dangerous Content</h3>
        <p><strong>Prohibited:</strong></p>
        <ul>
            <li>❌ <strong>Illegal Activities:</strong> Drug trafficking, weapons sales, human trafficking, etc.</li>
            <li>❌ <strong>Violent Content:</strong> Gory, horrific, or violent content</li>
            <li>❌ <strong>Child Safety:</strong> Any content involving minors</li>
            <li>❌ <strong>False Information:</strong> Spreading rumors, false news, or misleading information</li>
            <li>❌ <strong>Intellectual Property Infringement:</strong> Piracy, plagiarism, or unauthorized use</li>
        </ul>

        <h2>4. Fraud Prevention Guide</h2>
        
        <div class="important">
            <strong>🚨 Common Fraud Tactics</strong><br>
            Please be vigilant and avoid falling victim to these common scams:
        </div>

        <h3>🎭 Romance Scams</h3>
        <ul>
            <li>⚠️ Quickly expressing affection, claiming "love at first sight"</li>
            <li>⚠️ Fabricating tragic stories (sick family, financial difficulties)</li>
            <li>⚠️ Requesting money or "red envelopes" after establishing trust</li>
            <li>⚠️ Refusing video calls or meetings, always making excuses</li>
        </ul>

        <h3>💰 Investment Scams</h3>
        <ul>
            <li>⚠️ Promising "guaranteed profits" or "get rich quick"</li>
            <li>⚠️ Promoting cryptocurrencies, forex, or investment platforms</li>
            <li>⚠️ Requesting deposits or membership fees</li>
            <li>⚠️ Pressuring immediate decisions, claiming "limited-time offers"</li>
        </ul>

        <h3>🎁 Phishing Scams</h3>
        <ul>
            <li>⚠️ Sending suspicious links claiming "prizes" or "gifts"</li>
            <li>⚠️ Requesting passwords, verification codes, or bank accounts</li>
            <li>⚠️ Impersonating officials or customer service</li>
            <li>⚠️ Claiming account issues requiring "verification"</li>
        </ul>

        <h3>✅ How to Protect Yourself</h3>
        <div class="success">
            <strong>🛡️ Safety Tips:</strong><br>
            1. <strong>Never send money:</strong> XunNi will never ask you for money<br>
            2. <strong>Protect personal information:</strong> Do not disclose real name, address, phone number<br>
            3. <strong>Verify identities:</strong> Be skeptical of strangers' claims<br>
            4. <strong>Report suspicious behavior:</strong> Use <code>/report</code> command immediately<br>
            5. <strong>Trust your instincts:</strong> If something feels wrong, it probably is
        </div>

        <h2>5. Reporting and Blocking</h2>
        
        <h3>📢 How to Report</h3>
        <p>If you encounter violations, please report immediately:</p>
        <ol>
            <li>Use the <code>/report</code> command in conversation</li>
            <li>Select the reason for reporting (harassment, fraud, spam, etc.)</li>
            <li>Provide detailed description and evidence</li>
            <li>We will process within 24-48 hours</li>
        </ol>

        <h3>🚫 How to Block</h3>
        <p>If you don't want to continue communicating with someone:</p>
        <ol>
            <li>Use the <code>/block</code> command in conversation</li>
            <li>The other party will not be able to send you messages</li>
            <li>You will not be matched with them again</li>
            <li>You can unblock anytime</li>
        </ol>

        <h3>⚖️ Reporting Principles</h3>
        <div class="info">
            <strong>📌 Please Note:</strong><br>
            • Reports should be truthful and accurate<br>
            • Do not abuse the reporting system<br>
            • False reports may result in penalties<br>
            • All reports will be kept confidential
        </div>

        <h2>6. Penalties</h2>
        
        <h3>⚠️ Warning</h3>
        <p><strong>Applicable to:</strong></p>
        <ul>
            <li>First minor violation</li>
            <li>Unintentional inappropriate behavior</li>
        </ul>
        <p><strong>Consequence:</strong> Warning message, violation recorded</p>

        <h3>🚫 Temporary Ban</h3>
        <p><strong>Applicable to:</strong></p>
        <ul>
            <li>Repeated minor violations</li>
            <li>Moderate inappropriate behavior</li>
            <li>Spam or abuse</li>
        </ul>
        <p><strong>Consequence:</strong> Account banned for 1-30 days</p>

        <h3>🔒 Permanent Ban</h3>
        <p><strong>Applicable to:</strong></p>
        <ul>
            <li>Serious violations (fraud, harassment, illegal activities)</li>
            <li>Multiple repeated violations</li>
            <li>Threats to community safety</li>
        </ul>
        <p><strong>Consequence:</strong> Account permanently banned, reserve right to legal action</p>

        <h3>🙏 Appeal</h3>
        <p>If you believe a ban was issued in error:</p>
        <ul>
            <li>Use the <code>/appeal</code> command to submit an appeal</li>
            <li>Provide detailed reasons and evidence</li>
            <li>We will review within 3-7 business days</li>
            <li>Appeal decision is final</li>
        </ul>

        <h2>7. Privacy and Anonymity</h2>
        
        <h3>🎭 Respect Anonymity</h3>
        <ul>
            <li>✅ Respect others' choice to remain anonymous</li>
            <li>✅ Do not pressure others to disclose personal information</li>
            <li>✅ Do not attempt to identify or track others</li>
            <li>✅ Do not disclose others' information outside the platform</li>
        </ul>

        <h3>🔒 Protect Your Privacy</h3>
        <div class="highlight">
            <strong>💡 Privacy Protection Tips:</strong><br>
            • Do not disclose real name, address, phone number<br>
            • Do not share social media accounts or photos<br>
            • Do not disclose workplace or school information<br>
            • Be cautious about sharing location information<br>
            • Fully understand the other party before meeting
        </div>

        <h2>8. Healthy Communication Tips</h2>
        
        <h3>💬 How to Start a Good Conversation</h3>
        <ul>
            <li>✅ <strong>Friendly Greeting:</strong> Start with a simple greeting</li>
            <li>✅ <strong>Introduce Yourself:</strong> Share your interests and personality</li>
            <li>✅ <strong>Ask Open Questions:</strong> Encourage the other party to share</li>
            <li>✅ <strong>Listen Actively:</strong> Show genuine interest in the other party</li>
            <li>✅ <strong>Find Common Ground:</strong> Discover shared interests</li>
        </ul>

        <h3>🚫 How to End an Uncomfortable Conversation</h3>
        <ul>
            <li>✅ <strong>Politely Decline:</strong> "Sorry, I don't think we're a good match"</li>
            <li>✅ <strong>Use Block:</strong> Use <code>/block</code> command to end conversation</li>
            <li>✅ <strong>Report Violations:</strong> If the other party violates rules, report immediately</li>
            <li>✅ <strong>Don't Feel Guilty:</strong> You have the right to end any conversation</li>
        </ul>

        <h3>🌟 How to Be a Good Chat Partner</h3>
        <ul>
            <li>✅ <strong>Be Respectful:</strong> Respect others' opinions and feelings</li>
            <li>✅ <strong>Be Patient:</strong> Give the other party time to respond</li>
            <li>✅ <strong>Be Genuine:</strong> Maintain honest and authentic communication</li>
            <li>✅ <strong>Be Positive:</strong> Spread positive energy</li>
            <li>✅ <strong>Be Empathetic:</strong> Try to understand others' perspectives</li>
        </ul>

        <h2>9. Special Situations</h2>
        
        <h3>🆘 If You Encounter Danger</h3>
        <div class="important">
            <strong>⚠️ Emergency Situations</strong><br>
            If you encounter real-world danger or threats:
        </div>
        <ul>
            <li>🚨 <strong>Contact Law Enforcement Immediately:</strong> Dial emergency number (110, 911, etc.)</li>
            <li>🚨 <strong>Ensure Personal Safety:</strong> Leave dangerous environment</li>
            <li>🚨 <strong>Preserve Evidence:</strong> Save chat records and evidence</li>
            <li>🚨 <strong>Report to Platform:</strong> Use <code>/report</code> command to report</li>
        </ul>

        <h3>💔 If You Feel Uncomfortable</h3>
        <ul>
            <li>✅ <strong>Trust Your Feelings:</strong> If something feels wrong, it probably is</li>
            <li>✅ <strong>End Conversation:</strong> You have the right to end any conversation</li>
            <li>✅ <strong>Block User:</strong> Use <code>/block</code> command</li>
            <li>✅ <strong>Seek Support:</strong> Talk to friends or family</li>
        </ul>

        <h3>🤝 If You Witness Violations</h3>
        <ul>
            <li>✅ <strong>Report:</strong> Use <code>/report</code> command</li>
            <li>✅ <strong>Provide Evidence:</strong> Provide detailed information</li>
            <li>✅ <strong>Support Victims:</strong> Offer help and support if possible</li>
            <li>✅ <strong>Do Not Participate:</strong> Do not join in violations</li>
        </ul>

        <h2>10. Community Responsibility</h2>
        
        <div class="success">
            <strong>🌟 Building a Better Community Together</strong><br>
            Every user is an important member of the XunNi community. Your behavior directly affects the community atmosphere and experience.
        </div>

        <h3>👥 Your Responsibility</h3>
        <ul>
            <li>✅ <strong>Follow Guidelines:</strong> Comply with these Community Guidelines</li>
            <li>✅ <strong>Respect Others:</strong> Treat every user with respect</li>
            <li>✅ <strong>Report Violations:</strong> Help maintain community safety</li>
            <li>✅ <strong>Spread Positivity:</strong> Create a friendly communication environment</li>
            <li>✅ <strong>Lead by Example:</strong> Be a role model for others</li>
        </ul>

        <h3>🎯 Our Commitment</h3>
        <ul>
            <li>✅ <strong>Fair Enforcement:</strong> Handle all reports fairly and impartially</li>
            <li>✅ <strong>Transparent Communication:</strong> Clearly explain rules and penalties</li>
            <li>✅ <strong>Continuous Improvement:</strong> Continuously optimize community management</li>
            <li>✅ <strong>User Safety:</strong> Prioritize user safety and privacy</li>
        </ul>

        <h2>11. Contact Us</h2>
        
        <div class="info">
            <strong>📧 For any questions or suggestions, please contact us:</strong><br><br>
            <strong>Telegram:</strong> @xunni_support (Support Bot)<br>
            <strong>Email:</strong> support@xunni.app (if applicable)<br><br>
            We will respond to your request within 7 business days.
        </div>

        <h2>12. Guidelines Updates</h2>
        
        <p>We may update these Community Guidelines from time to time. For significant changes:</p>
        <ul>
            <li>📢 We will send notifications in the Bot</li>
            <li>📢 The update date will be displayed at the top of the page</li>
            <li>📢 Continued use of the service indicates your acceptance of the updated guidelines</li>
        </ul>

        <hr style="margin: 40px 0; border: none; border-top: 1px solid #ddd;">

        <div class="success" style="text-align: center;">
            <strong>✨ Thank you for reading!</strong><br>
            Let's work together to create a safe, friendly, and respectful XunNi community!<br>
            🤝 Respect | 🛡️ Safety | 🌈 Inclusivity | 💙 Authenticity
        </div>

        <hr style="margin: 40px 0; border: none; border-top: 1px solid #ddd;">

        <p style="text-align: center; color: #7f8c8d; font-size: 14px;">
            © 2025 XunNi. All rights reserved.<br>
            <a href="terms.html">Terms of Service</a> | 
            <a href="privacy.html">Privacy Policy</a> | 
            <a href="community.html">Community Guidelines</a>
        </p>
    </div>
</body>
</html>
`,
} as const;

/**
 * Get legal document HTML content
 */
export function getLegalDocument(type: 'privacy' | 'terms' | 'community'): string {
  return LEGAL_DOCUMENTS[type];
}

/**
 * Serve legal document as HTTP response
 */
export function serveLegalDocument(type: 'privacy' | 'terms' | 'community'): Response {
  const content = getLegalDocument(type);

  return new Response(content, {
    status: 200,
    headers: {
      'Content-Type': 'text/html; charset=utf-8',
      'Cache-Control': 'public, max-age=3600', // Cache for 1 hour
      'X-Content-Type-Options': 'nosniff',
    },
  });
}
